tasks:
  - init: >
      wget -qOdatabase-setup.sh https://codejudge-starter-repo-artifacts.s3.ap-south-1.amazonaws.com/backend-project/gitpod/node/17.0.0/db-gitpod-setup.sh &&
      chmod 0755 db-gitpod-setup.sh &&
      bash db-gitpod-setup.sh
ports:
  - port: 8080
    onOpen: ignore
    visibility: public
